version: '3.8'

services:
    postgres:
        image: postgres:12.4-alpine

    php_fpm:
        build: ./docker/build/dev/php

    nginx:
        image: nginx:1.19.2-alpine

    redis:
        image: redis:6.0.8-alpine
